### ISSUE TITLE
custom source dirctory

### ISSUE THREAD

**Issue by bcardarella** [jonathantneal/postcss-svg-fragments#10]
From what I can see the plugin doesn't provide a way to set a custom source directory. Is this possible?

**Comment by jonathantneal** [comment]
It is possible in the next version, which also supports inlining svgs, which begs me to question whether I should just make a PR against inline-svg to support fragments.

**Comment by jonathantneal** [comment]
Good news. Bad news.

Bad news. This plugin is no longer maintained! Hope is not lost.

Good news. That feature was [added](https://github.com/jonathantneal/postcss-svg#advanced-usage) when work was moved to [PostCSS SVG](https://github.com/jonathantneal/postcss-svg).
