### ISSUE TITLE
Async loading

### ISSUE THREAD

**Issue by TrySound** [jonathantneal/postcss-svg-fragments#2]
As said in guidelines. You should use async functions whenever possible
https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#22-use-asynchronous-methods-whenever-possible

**Comment by jonathantneal** [comment]
Busted. You found my `readFileSync`. This will be resolved in a future release.

**Comment by jonathantneal** [comment]
Thanks, @TrySound. There was actually quite a bit to change, because I had not been caching the SVGs. Resolved in [v1.2.0](https://github.com/jonathantneal/postcss-svg-fragments/tree/v1.2.0)
