### ISSUE TITLE
Doesn't support LTS version of Node 4.

### ISSUE THREAD

**Issue by niccai** [jonathantneal/postcss-svg-fragments#8]
The switch to ES6 has made this plugin incompatible with Node 4 LTS.  Might be worth noting for others.  I'm not suggesting it has to be fixed.  To easily switch between node versions for different projects, people can use [n](https://github.com/tj/n).

**Comment by jonathantneal** [comment]
It’s good of you to mention it. It’s noted in [`CHANGELOG.MD`](https://github.com/jonathantneal/postcss-svg-fragments/blob/master/CHANGELOG.md#200-december-6-2016) and made explicit in [`package.json`](https://github.com/jonathantneal/postcss-svg-fragments/blob/master/package.json#L23-L25). I’ve updated both references to clarify Node v6.5.0+ LTS compatibility.
